// Guidance texts based on mood selection
export const guidanceTexts: Record<string, string[]> = {
  great: [
    "You are radiating confidence and positive energy today.",
    "You acknowledge your strengths and celebrate your progress.",
    "Every challenge you overcome makes you stronger.",
    "You are grateful for this moment of joy and clarity.",
    "Your positive energy influences those around you.",
    "You choose to focus on what's going well in your life.",
    "You are worthy of this happiness and all good things.",
    "Today you embrace your potential and limitless possibilities.",
    "You are exactly where you need to be on your journey.",
    "Your happiness comes from within and you nurture it daily.",
    "You attract positive experiences through your optimistic outlook.",
    "You are creating a life that feels good on the inside.",
    "Your confidence grows stronger each day.",
    "You celebrate the small victories that lead to great achievements.",
    "You are becoming the best version of yourself.",
    "You trust in your ability to create positive change.",
    "Your mind is clear, your heart is open, your spirit is strong.",
    "You are aligned with your purpose and values.",
    "You embrace each moment with enthusiasm and gratitude.",
    "Your positive mindset creates beautiful opportunities.",
    "You are proud of who you are becoming.",
    "You radiate love and positive energy wherever you go.",
    "You are in harmony with yourself and the world around you.",
    "Today you choose joy, peace, and fulfillment.",
    "You are a magnet for success and happiness.",
  ],
  
  good: [
    "You are on the right path, taking one positive step at a time.",
    "You appreciate the balance and stability in your life today.",
    "Your efforts are creating meaningful progress.",
    "You choose to focus on solutions rather than problems.",
    "You are building momentum toward your goals and dreams.",
    "You embrace both your strengths and areas for growth.",
    "Today you notice and appreciate the simple pleasures.",
    "You are becoming more resilient and adaptable each day.",
    "Your positive choices create ripples of good in your life.",
    "You are learning to trust the process of your journey.",
    "You are grateful for this steady, positive energy.",
    "You acknowledge your progress, no matter how small.",
    "You are creating a life aligned with your values.",
    "Each day brings new opportunities for your growth and joy.",
    "You are worthy of good things and positive experiences.",
    "You choose to see possibilities rather than limitations.",
    "Your well-being matters, and you prioritize it today.",
    "You are cultivating peace and contentment in your daily life.",
    "You appreciate the balance between effort and ease.",
    "Today you choose to be kind to yourself and others.",
  ],
  
  okay: [
    "It's okay to simply be. What small joy can you notice right now?",
    "You honor your need for balance and rest.",
    "This moment of stillness is a gift for you.",
    "You accept where you are today while gently moving forward.",
    "You are exactly where you need to be on your journey.",
    "What would feel nourishing for you right now?",
    "You give yourself permission to be perfectly imperfect.",
    "Today you practice patience with yourself and your process.",
    "You acknowledge your feelings without judgment.",
    "Small steps forward still create meaningful progress for you.",
    "You trust that you have the resources to navigate this day.",
    "What one small thing could bring you joy today?",
    "You are learning to find peace in the present moment.",
    "You choose to be gentle with yourself today.",
    "Balance doesn't mean perfect equilibrium every day for you.",
    "You honor both your strengths and your struggles.",
    "Today you practice self-compassion and understanding.",
    "You are allowed to take things one moment at a time.",
    "What would feel like self-care for you right now?",
    "You acknowledge that neutral moments are also valuable.",
  ],
  
  challenged: [
    "This feeling is a visitor, not a resident. It will pass.",
    "You have overcome difficulties before; you have the strength within you.",
    "You choose to respond with kindness to yourself in this moment.",
    "Take three slow, deep breaths. You are safe.",
    "What would you say to a friend facing this challenge?",
    "You acknowledge this difficulty while knowing it doesn't define you.",
    "One step at a time is all you need to focus on right now.",
    "You are learning valuable lessons through this challenge.",
    "You give yourself permission to take a break when needed.",
    "Your worth is not determined by your productivity or success.",
    "You can be both a work in progress and worthy of love.",
    "This challenge is developing your resilience and strength.",
    "You trust in your ability to navigate difficult emotions.",
    "What small action could bring you comfort right now?",
    "You are allowed to ask for help when you need it.",
    "You acknowledge your feelings without being defined by them.",
    "This moment is teaching you something valuable.",
    "You choose to be patient and gentle with yourself today.",
    "You have the inner resources to face this challenge.",
    "What would feel like an act of self-compassion right now?",
  ],
  
  struggling: [
    "You acknowledge your pain with compassion. This too shall pass.",
    "Even in darkness, you carry an inner light that cannot be extinguished.",
    "You give yourself permission to feel without judgment.",
    "One breath at a time. You are surviving this moment.",
    "You are not alone in your struggles, even when it feels that way.",
    "Your worth remains unchanged, regardless of what you're going through.",
    "You honor your journey, including the difficult chapters.",
    "What is one tiny thing you can do to care for yourself right now?",
    "You release the pressure to have it all figured out.",
    "This struggle is part of your story, not the whole story.",
    "You are allowed to take things one moment at a time.",
    "You trust that this difficult time holds purpose and meaning.",
    "You give yourself permission to rest and recover.",
    "Your feelings are valid, and you honor them with compassion.",
    "You are stronger than you feel in this moment.",
    "What would feel like a small act of kindness toward yourself?",
    "You release the need to be perfect or have perfect days.",
    "You are learning to navigate difficult emotions with grace.",
    "You choose to be gentle with yourself during this challenging time.",
    "This moment does not define your entire journey.",
    "You acknowledge your pain while knowing you are more than your struggles.",
    "You are worthy of support and compassion, especially when hurting.",
    "You trust in your resilience and ability to heal.",
    "What small comfort can you offer yourself right now?",
    "You are doing the best you can with what you have in this moment.",
  ],
};

// Function to get a random guidance text based on mood
export const getRandomGuidance = (mood: string): string => {
  const texts = guidanceTexts[mood];
  const randomIndex = Math.floor(Math.random() * texts.length);
  return texts[randomIndex];
};