import { MoodType } from './moods';

// Guidance texts based on mood selection
export const guidanceTexts: Record<MoodType, string[]> = {
  great: [
    "I am radiating confidence and positive energy today.",
    "I acknowledge my strengths and celebrate my progress.",
    "Every challenge I overcome makes me stronger.",
    "I am grateful for this moment of joy and clarity.",
    "My positive energy influences those around me.",
    "I choose to focus on what's going well in my life.",
    "I am worthy of this happiness and all good things.",
    "Today I embrace my potential and limitless possibilities.",
    "I am exactly where I need to be on my journey.",
    "My happiness comes from within and I nurture it daily.",
    "I attract positive experiences through my optimistic outlook.",
    "I am creating a life that feels good on the inside.",
    "My confidence grows stronger each day.",
    "I celebrate the small victories that lead to great achievements.",
    "I am becoming the best version of myself.",
    "I trust in my ability to create positive change.",
    "My mind is clear, my heart is open, my spirit is strong.",
    "I am aligned with my purpose and values.",
    "I embrace each moment with enthusiasm and gratitude.",
    "My positive mindset creates beautiful opportunities.",
    "I am proud of who I am becoming.",
    "I radiate love and positive energy wherever I go.",
    "I am in harmony with myself and the world around me.",
    "Today I choose joy, peace, and fulfillment.",
    "I am a magnet for success and happiness.",
  ],
  
  good: [
    "I am on the right path, taking one positive step at a time.",
    "I appreciate the balance and stability in my life today.",
    "My efforts are creating meaningful progress.",
    "I choose to focus on solutions rather than problems.",
    "I am building momentum toward my goals and dreams.",
    "I embrace both my strengths and areas for growth.",
    "Today I notice and appreciate the simple pleasures.",
    "I am becoming more resilient and adaptable each day.",
    "My positive choices create ripples of good in my life.",
    "I am learning to trust the process of my journey.",
    "I am grateful for this steady, positive energy.",
    "I acknowledge my progress, no matter how small.",
    "I am creating a life aligned with my values.",
    "Each day brings new opportunities for growth and joy.",
    "I am worthy of good things and positive experiences.",
    "I choose to see possibilities rather than limitations.",
    "My well-being matters, and I prioritize it today.",
    "I am cultivating peace and contentment in my daily life.",
    "I appreciate the balance between effort and ease.",
    "Today I choose to be kind to myself and others.",
  ],
  
  okay: [
    "It's okay to simply be. What small joy can I notice right now?",
    "I honor my need for balance and rest.",
    "This moment of stillness is a gift.",
    "I accept where I am today while gently moving forward.",
    "I am exactly where I need to be on my journey.",
    "What would feel nourishing for me right now?",
    "I give myself permission to be perfectly imperfect.",
    "Today I practice patience with myself and my process.",
    "I acknowledge my feelings without judgment.",
    "Small steps forward still create meaningful progress.",
    "I trust that I have the resources to navigate this day.",
    "What one small thing could bring me joy today?",
    "I am learning to find peace in the present moment.",
    "I choose to be gentle with myself today.",
    "Balance doesn't mean perfect equilibrium every day.",
    "I honor both my strengths and my struggles.",
    "Today I practice self-compassion and understanding.",
    "I am allowed to take things one moment at a time.",
    "What would feel like self-care for me right now?",
    "I acknowledge that neutral moments are also valuable.",
  ],
  
  challenged: [
    "This feeling is a visitor, not a resident. It will pass.",
    "I have overcome difficulties before; I have the strength within me.",
    "I choose to respond with kindness to myself in this moment.",
    "Take three slow, deep breaths. You are safe.",
    "What would I say to a friend facing this challenge?",
    "I acknowledge this difficulty while knowing it doesn't define me.",
    "One step at a time is all I need to focus on right now.",
    "I am learning valuable lessons through this challenge.",
    "I give myself permission to take a break when needed.",
    "My worth is not determined by my productivity or success.",
    "I can be both a work in progress and worthy of love.",
    "This challenge is developing my resilience and strength.",
    "I trust in my ability to navigate difficult emotions.",
    "What small action could bring me comfort right now?",
    "I am allowed to ask for help when I need it.",
    "I acknowledge my feelings without being defined by them.",
    "This moment is teaching me something valuable.",
    "I choose to be patient and gentle with myself today.",
    "I have the inner resources to face this challenge.",
    "What would feel like an act of self-compassion right now?",
  ],
  
  struggling: [
    "I acknowledge my pain with compassion. This too shall pass.",
    "Even in darkness, I carry an inner light that cannot be extinguished.",
    "I give myself permission to feel without judgment.",
    "One breath at a time. I am surviving this moment.",
    "I am not alone in my struggles, even when it feels that way.",
    "My worth remains unchanged, regardless of what I'm going through.",
    "I honor my journey, including the difficult chapters.",
    "What is one tiny thing I can do to care for myself right now?",
    "I release the pressure to have it all figured out.",
    "This struggle is part of my story, not the whole story.",
    "I am allowed to take things one moment at a time.",
    "I trust that this difficult time holds purpose and meaning.",
    "I give myself permission to rest and recover.",
    "My feelings are valid, and I honor them with compassion.",
    "I am stronger than I feel in this moment.",
    "What would feel like a small act of kindness toward myself?",
    "I release the need to be perfect or have perfect days.",
    "I am learning to navigate difficult emotions with grace.",
    "I choose to be gentle with myself during this challenging time.",
    "This moment does not define my entire journey.",
    "I acknowledge my pain while knowing I am more than my struggles.",
    "I am worthy of support and compassion, especially when hurting.",
    "I trust in my resilience and ability to heal.",
    "What small comfort can I offer myself right now?",
    "I am doing the best I can with what I have in this moment.",
  ],
};

// Function to get a random guidance text based on mood
export const getRandomGuidance = (mood: MoodType): string => {
  const texts = guidanceTexts[mood];
  const randomIndex = Math.floor(Math.random() * texts.length);
  return texts[randomIndex];
};